### ISSUE TITLE
Create TTL Node shows invalid arguments

### ISSUE THREAD

**Issue by Mengyantong** [go-zookeeper/zk#119]
I am facing an issue while attempting to create a TTL node. During the execution of the corresponding function, I consistently encounter an "invalid arguments" error. My parameters align with the function definition, yet the error persists. Could it be that I am using the function incorrectly?
My code like:
`res, err := conn.CreateTTL("/testpath", []byte("ttl node"), zk.FlagTTL, zk.WorldACL(zk.PermAll), time.Second)
`

**Comment by Mengyantong** [comment]
The code is fine, the reason is that TTL nodes are not enabled in my Zookeeper server. Note that starting from 3.5.3, Zookeeper supports the creation of Time-To-Live (TTL) nodes, but we may need manually add these 2 setting and restart the Zookeeper server.

**Comment by alandiegosantos** [comment]
The FlagTTL in go-zookeeper/zk is wrong. The [CreateMode flag of PERSISTENT_WITH_TTL is 5](https://github.com/apache/zookeeper/blob/d12aba599233b0fcba0b9b945ed3d2f45d4016f0/zookeeper-server/src/main/java/org/apache/zookeeper/CreateMode.java#L64) in zookeeper code while in the go-zookeeper/zk is 4. In this case, the Create is trying to create a Container instead of a persistent node with TTL.

I will push a PR to fix this.
